### ISSUE TITLE
Pedestal import export rf -4800

### ISSUE THREAD

**Issue by Ptituf** [Mowmaster/Pedestals#99] opened 2021-07-14 22:23 UTC
I don't know if i am missing something and guess yes but my
Pedestal export using 5000/t on transfer but the Pedestal import get 200/t
so im loosing 4800 rf /tick and i dont know why

Modpack Enigmatica 6 v 0.5.4
![5000bananas](https://user-images.githubusercontent.com/28937889/125700588-58fbf35f-f5b8-46f8-872a-62a51144925c.PNG)
![5000proof](https://user-images.githubusercontent.com/28937889/125700626-0e6675a7-206d-4bff-ac07-44f4ffcb28de.PNG)
![200fe](https://user-images.githubusercontent.com/28937889/125700640-cf7ae4e1-886b-4ddd-a86b-5623e44d02f7.PNG)
![borred](https://user-images.githubusercontent.com/28937889/125700657-c1558a98-d184-4281-90de-a25e074b43d6.PNG)

**Comment by Ptituf** [comment] 2021-07-14 22:25
Its a multiple test , that why you can see "3 pedestal" but its  only 2 , i moved and relinked to proove the -5000 on the energy cell

**Comment by Mowmaster** [comment] 2021-07-15 03:07
okay given your description it was a little difficult to understand, but after some testing in the pack it does seem like some mods energy cubes interact poorly with pedestals, Mekanism and Integrated Dynamics seem to be working as intended but Thermal and Powah cells seem to push more power into the importer then it can hold, resulting in voiding energy happening. Im not sure what 2/4 of the mods are doing differently but ill consider this a bug on my end.
One way to potentially resolve this, is to enchant the upgrade with speed 5, this will allow it to insert/extract energy at a per tick (/t) rate instead of the per second rate its at currently given your images.

**Comment by Ptituf** [comment] 2021-07-15 11:08
Okay thank you for the quick response and sorry for the poor description at the beginning. With your explanation i anderstand i was in second instead of tick . So tick to second is /20 and 5000/20 is 250 but why i get 200 anyway ? Best regards.

**Comment by Mowmaster** [comment] 2021-07-19 05:40
https://github.com/Mowmaster/Pedestals/commit/a717e6e0cfee2bbf7313e8f09375f718d079b4d4

**Comment by Mowmaster** [comment] 2021-11-08 01:12
apparently when i was testing i used the higher leveled machines that an accept power, so now the pedestal is pushing up to its max limit of energy but if a machine restricts the input, then the pedestal voids the difference in power. noticing this issue with the basic powah cells and the energy cube thingy from Thermal mods.

**Comment by Mowmaster** [comment] 2022-06-22 19:14
Closing all 1.16 issues, as I am no longer supporting this version of the game and 1.19+ is a full rewrite, I will however accept and merge any fixes folks make for this version.

**Closed** 2022-06-22 19:14 UTC
Labels: bug
